# --- General Parameters ---
project_name: cfd_hedging_analysis
initial_capital: 1000000.0
equity_allocation: 0.80
trading_days_per_year: 252
# Using 360 for financing cost calculation as per source material
days_in_year_financing: 360

# --- Data ---
data_file: data/vix_sp500_data.csv
date_column: date
sp500_column: S&P500
vix_column: VIX
sofr_column: SOFR

# --- Hedging Strategy ---
vix_threshold: 25.0
hedge_ratio: 0.50 # Percentage of equity value to hedge

# --- CFD Cost Model (Based on IG Markets assumptions in source) ---
# Note: Spread cost is applied per round trip when closing hedge
avg_spread_points: 0.7 # In index points
lot_size: 1.0 # USD value per index point for CFD
# Broker annual fee added/subtracted from benchmark for financing
broker_annual_financing_fee: 0.03 # 3%
# Borrowing cost specific to short CFD positions
borrowing_cost_annual: 0.006 # 0.6%

# CFD Margin Tiers (Rate applied to notional value for contracts in tier)
margin_tiers:
  - limit: 5      # Up to 5 contracts
    rate: 0.005   # 0.5%
  - limit: 25     # From 5 up to 25 contracts
    rate: 0.01    # 1.0%
  - limit: 40     # From 25 up to 40 contracts
    rate: 0.03    # 3.0%
  - limit: .inf   # Any contracts above 40
    rate: 0.15    # 15.0%

# --- Analysis ---
# Crisis Period Definitions
crisis_periods:
  covid_19:
    start: '2020-02-15'
    end: '2020-04-30'
  hypothetical_2025:
    start: '2025-03-01'
    end: '2025-05-15'

# --- Plotting ---
plot_output_dir: outputs/plots/ # Optional: Directory to save plots
save_plots: false # Whether to save plots when running run.py
